const cmdId = {
    ADD_LOVE_PET: CommandID.ADD_LOVE_PET,
    COUNTERMARK_RESOLVE: CommandID.COUNTERMARK_RESOLVE,
    DEL_LOVE_PET: CommandID.DEL_LOVE_PET,
    ITEM_BUY: CommandID.ITEM_BUY,
    GET_COUNTERMARK_LIST2: CommandID.GET_COUNTERMARK_LIST2,
    GET_MULTI_FOREVER: CommandID.GET_MULTI_FOREVER,
    NOTE_USE_SKILL: CommandID.NOTE_USE_SKILL,
    PET_ONE_CURE: CommandID.PET_ONE_CURE,
    PET_RELEASE: CommandID.PET_RELEASE,
    SAVE_COUNTERMARK_PROPERTY: CommandID.SAVE_COUNTERMARK_PROPERTY,
    STRENGTHEN_COUNTERMARK: CommandID.STRENGTHEN_COUNTERMARK,
    USE_PET_ITEM_OUT_OF_FIGHT: CommandID.USE_PET_ITEM_OUT_OF_FIGHT,
};
export { cmdId as SA_CONST_CMDID };

