const cmdId = {
    ADD_LOVE_PET: CommandID.ADD_LOVE_PET,
    DEL_LOVE_PET: CommandID.DEL_LOVE_PET,
    ITEM_BUY: CommandID.ITEM_BUY,
    GET_MULTI_FOREVER: CommandID.GET_MULTI_FOREVER,
    NOTE_USE_SKILL: CommandID.NOTE_USE_SKILL,
    PET_ONE_CURE: CommandID.PET_ONE_CURE,
    PET_RELEASE: CommandID.PET_RELEASE,
    USE_PET_ITEM_OUT_OF_FIGHT: CommandID.USE_PET_ITEM_OUT_OF_FIGHT,
};
export { cmdId as SA_CONST_CMDID };
